/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SalesHistoryRouteImport } from './routes/sales-history'
import { Route as SalesRouteImport } from './routes/sales'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InvoiceUploadRouteImport } from './routes/invoice-upload'
import { Route as InvoiceHistoryRouteImport } from './routes/invoice-history'
import { Route as InventoryRouteImport } from './routes/inventory'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CartRouteImport } from './routes/cart'
import { Route as BillingRouteImport } from './routes/billing'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppAlertsRouteImport } from './routes/_app.alerts'

const SalesHistoryRoute = SalesHistoryRouteImport.update({
  id: '/sales-history',
  path: '/sales-history',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesRoute = SalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoiceUploadRoute = InvoiceUploadRouteImport.update({
  id: '/invoice-upload',
  path: '/invoice-upload',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoiceHistoryRoute = InvoiceHistoryRouteImport.update({
  id: '/invoice-history',
  path: '/invoice-history',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryRoute = InventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingRoute = BillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAlertsRoute = AppAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/billing': typeof BillingRoute
  '/cart': typeof CartRoute
  '/dashboard': typeof DashboardRoute
  '/inventory': typeof InventoryRoute
  '/invoice-history': typeof InvoiceHistoryRoute
  '/invoice-upload': typeof InvoiceUploadRoute
  '/login': typeof LoginRoute
  '/orders': typeof OrdersRoute
  '/profile': typeof ProfileRoute
  '/sales': typeof SalesRoute
  '/sales-history': typeof SalesHistoryRoute
  '/alerts': typeof AppAlertsRoute
}
export interface FileRoutesByTo {
  '/billing': typeof BillingRoute
  '/cart': typeof CartRoute
  '/dashboard': typeof DashboardRoute
  '/inventory': typeof InventoryRoute
  '/invoice-history': typeof InvoiceHistoryRoute
  '/invoice-upload': typeof InvoiceUploadRoute
  '/login': typeof LoginRoute
  '/orders': typeof OrdersRoute
  '/profile': typeof ProfileRoute
  '/sales': typeof SalesRoute
  '/sales-history': typeof SalesHistoryRoute
  '/alerts': typeof AppAlertsRoute
  '/': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/billing': typeof BillingRoute
  '/cart': typeof CartRoute
  '/dashboard': typeof DashboardRoute
  '/inventory': typeof InventoryRoute
  '/invoice-history': typeof InvoiceHistoryRoute
  '/invoice-upload': typeof InvoiceUploadRoute
  '/login': typeof LoginRoute
  '/orders': typeof OrdersRoute
  '/profile': typeof ProfileRoute
  '/sales': typeof SalesRoute
  '/sales-history': typeof SalesHistoryRoute
  '/_app/alerts': typeof AppAlertsRoute
  '/_app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/billing'
    | '/cart'
    | '/dashboard'
    | '/inventory'
    | '/invoice-history'
    | '/invoice-upload'
    | '/login'
    | '/orders'
    | '/profile'
    | '/sales'
    | '/sales-history'
    | '/alerts'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/billing'
    | '/cart'
    | '/dashboard'
    | '/inventory'
    | '/invoice-history'
    | '/invoice-upload'
    | '/login'
    | '/orders'
    | '/profile'
    | '/sales'
    | '/sales-history'
    | '/alerts'
    | '/'
  id:
    | '__root__'
    | '/_app'
    | '/billing'
    | '/cart'
    | '/dashboard'
    | '/inventory'
    | '/invoice-history'
    | '/invoice-upload'
    | '/login'
    | '/orders'
    | '/profile'
    | '/sales'
    | '/sales-history'
    | '/_app/alerts'
    | '/_app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  BillingRoute: typeof BillingRoute
  CartRoute: typeof CartRoute
  DashboardRoute: typeof DashboardRoute
  InventoryRoute: typeof InventoryRoute
  InvoiceHistoryRoute: typeof InvoiceHistoryRoute
  InvoiceUploadRoute: typeof InvoiceUploadRoute
  LoginRoute: typeof LoginRoute
  OrdersRoute: typeof OrdersRoute
  ProfileRoute: typeof ProfileRoute
  SalesRoute: typeof SalesRoute
  SalesHistoryRoute: typeof SalesHistoryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sales-history': {
      id: '/sales-history'
      path: '/sales-history'
      fullPath: '/sales-history'
      preLoaderRoute: typeof SalesHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales': {
      id: '/sales'
      path: '/sales'
      fullPath: '/sales'
      preLoaderRoute: typeof SalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoice-upload': {
      id: '/invoice-upload'
      path: '/invoice-upload'
      fullPath: '/invoice-upload'
      preLoaderRoute: typeof InvoiceUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoice-history': {
      id: '/invoice-history'
      path: '/invoice-history'
      fullPath: '/invoice-history'
      preLoaderRoute: typeof InvoiceHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing': {
      id: '/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof BillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/alerts': {
      id: '/_app/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AppAlertsRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAlertsRoute: typeof AppAlertsRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAlertsRoute: AppAlertsRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  BillingRoute: BillingRoute,
  CartRoute: CartRoute,
  DashboardRoute: DashboardRoute,
  InventoryRoute: InventoryRoute,
  InvoiceHistoryRoute: InvoiceHistoryRoute,
  InvoiceUploadRoute: InvoiceUploadRoute,
  LoginRoute: LoginRoute,
  OrdersRoute: OrdersRoute,
  ProfileRoute: ProfileRoute,
  SalesRoute: SalesRoute,
  SalesHistoryRoute: SalesHistoryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
